### PR TITLE
Implement warn function

### PR DESCRIPTION
**Pull request by RadiantUwU**
This will call push_warning once lua executes warn()

### CODE REVIEW

**Comment by Trey2k** [comment]
I like the idea of this, however using the built in godot warning print should just be default. User should be able to  set their own warnf method as well imo

**Comment by RadiantUwU** [comment]
> I like the idea of this, however using the built in godot warning print should just be default. User should be able to set their own warnf method as well imo

That could always be added later, they could also just push a new global with warn() to make it easy, but by default it should still use push_warning as expected.

**Comment by Trey2k** [comment]
> That could always be added later, they could also just push a new global with warn() to make it easy, but by default it should still use push_warning as expected.

IMO the ability to prevent the warning output from going to through the build in warning system is a must. Since the lua API allows a special method to be set for the warning (special as in its not a lua_CFunction) there should be a method like we have for set_hook but for the warning. Where possible we just want to expose a convenient version of the base lua API

**Comment by RadiantUwU** [comment]
> IMO the ability to prevent the warning output from going to through the build in warning system is a must. Since the lua API allows a special method to be set for the warning (special as in its not a lua_CFunction) there should be a method like we have for set_hook but for the warning. Where possible we just want to expose a convenient version of the base lua API

I could try adding one, just a private callable member would work?

**Comment by Trey2k** [comment]
> I could try adding one, just a private callable member would work?

Yeah just a callable that if it exists it is called to handle the warning instead of the build in handling you have done.

**Comment by RadiantUwU** [comment]
Ummmm, it seems like i will have to move the implementation over to luaState....

**Comment by RadiantUwU** [comment]
bruh

**Comment by RadiantUwU** [comment]
Oops, i forgor :skull:

**Pull request closed without merging**
